LearnWeb/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import views
from LearnWeb.settings import ROOT_URL

urlpatterns = [
    path('admin/',admin.site.urls),
    path('blog/',views.blog),
    path(r'%s' %ROOT_URL[1:], include('LearnWeb.real_urls')),
    path('polls/',include('polls.urls')),
    path('cms/',include('cms.urls')),
]

cms/urls.py
from django.urls import path
from . import views
from .models import Story

app_name='cms'
urlpatterns=[
    path(r'^<slug:slug>/',views.story_detail,name='story'),
    path(r'',views.story_list,name='home'),
    path(r'category/<slug:slug>/',views.category,name='category'),
    path(r'search/',views.search,name='search'),
]

photogallery/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path('',index,name='index'),
]

polls/urls.py
from django.urls import path

from . import views

app_name='polls'
urlpatterns=[
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/results/',views.results,name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote')
]

blog/models.py
from django.db import models
from django.contrib import admin

class BlogPost(models.Model):
    title=models.CharField(max_length=10)
    body=models.TextField()
    timestamp=models.DateTimeField()

class BlogPostAdmin(admin.ModelAdmin):
    list_display = ('title','timestamp')

admin.site.register(BlogPost,BlogPostAdmin)

cms/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.contrib import admin
from markdown import markdown

VIEWABLE_STATUS=[3,4]

class ViewableManager(models.Manager):
    def get_queryset(self):
        default_queryset=super(ViewableManager,self).get_queryset()
        return default_queryset.filter(status__in=VIEWABLE_STATUS)


class Category(models.Model):
    label=models.CharField(blank=True,max_length=50)
    slug=models.SlugField()

    class Meta:
        verbose_name_plural='categories'

    def __unicode__(self):
        return self.label

class CategoryAdmin(admin.ModelAdmin):
    prepopulated_fields = {'slug':('label',)}


class Story(models.Model):
    STATUS_CHOICES=(
        (1,"Needs edits"),
        (2,"Needs Approval"),
        (3,"Published"),
        (4,"Achived")
    )
    title=models.CharField(max_length=100)
    slug=models.SlugField()
    category=models.ForeignKey(Category,on_delete=True)
    markdown_content=models.TextField()
    html_content=models.TextField(editable=False)
    owner=models.ForeignKey(User,on_delete=True)
    status=models.IntegerField(choices=STATUS_CHOICES,default=1)
    created=models.DateTimeField(default=datetime.datetime.now)
    modified=models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        ordering=['modified']
        verbose_name_plural='stories'

    admin_objects = models.Manager()
    objects = ViewableManager()
    def save(self):
        self.html_content=markdown(self.markdown_content)
        self.modified=datetime.datetime.now()
        super(Story,self).save()



class StoryAdmin(admin.ModelAdmin):
    list_display = ('title','owner','status','created','modified')
    search_fields = ('title','content')
    list_filter = ('status','owner','created','modified')
    prepopulated_fields = {'slug':('title',)}



admin.site.register(Category,CategoryAdmin)


admin.site.register(Story,StoryAdmin)

photogallery/models.py
from django.db import models
from django.contrib import admin
from .fields import ThumbnailImageField
#from django.db.models import permalink

class Item(models.Model):
    name=models.CharField(max_length=100)
    description=models.TextField()

    class Meta:
        ordering=['name']

    def __unicode__(self):
        return self.name

    #@permalink
    def get_absolute_url(self):
        return ('Item_detail',None,{'object_id':self.id})

class Photo(models.Model):
    item=models.ForeignKey(Item,on_delete=True)
    title=models.CharField(max_length=100)
    image=ThumbnailImageField(upload_to='photos')
    caption=models.CharField(max_length=100,blank=True)

    class Meta:
        ordering=['title']

    def __unicode__(self):
        return self.title

    #@permalink
    def get_absolute_url(self):
        return ('Photo_detail',None,{'object_id':self.id})

class PhotoInline(admin.StackedInline):
    model = Photo

class ItemAdmin(admin.ModelAdmin):
    inlines = [PhotoInline]

admin.site.register(Item,ItemAdmin)
admin.site.register(Photo)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=100)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=100)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.shortcuts import render
from blog.models import BlogPost

def blog(request):
    posts=BlogPost.objects.all()
    c={}
    c['posts']=posts
    return render(request,'blog.html',c)

cms/views.py
from django.shortcuts import render,get_object_or_404
from django.db.models import Q
from cms.models import Story,Category
from django.views import generic

# Create your views here.
def category(request,slug):
    category=get_object_or_404(Category,slug=slug)
    story_list=Story.objects.filter(category=category)
    heading='Category:%s' % category.label
    return render(request,'cms/story_list.html',locals())

def search(request):
    print('search')
    if 'q' in request.GET:
        term=request.GET['q']
        story_list=Story.objects.filter(Q(title__contains=term)|Q
                                        (markdown_content__contains=term))
        heading='Search results'
    return render(request,'cms/story_list.html',locals())


def story_detail(request,slug):
    print('abcd')
    story=get_object_or_404(Story,slug=slug)
    heading='Story:%s' % slug
    return render(request,'cms/story_detail.html',locals())

def story_list(request):
    story_list=Story.objects.all()
    return render(request,'cms/story_list.html',locals())

photogallery/views.py
from django.shortcuts import render
from .models import Photo,Item
# Create your views here.
def index(request):
    items=Item.objects.all()
    c={}
    c['items']=items
    return render(request,'index.html',c)

polls/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from .models import Question
from django.urls import reverse

# polls.views

def index(request):
    latest_question_list=Question.objects.order_by('-pub_date')[:5]
    c={}
    c['latest_question_list']=latest_question_list
    return render(request,'polls/index.html',c)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    c={'question': question}
    print(c)
    return render(request, 'polls/detail.html', c)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError):
        return render(request,'polls/detail.html',{
            'question':question,
            'error_message':"You didn't select a choice.",
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

cms/templates/cms/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css" media="screen">
        body {margin:15px;font-family: Arial;}
        h1,h2 {background: #aaa;padding:1% 2%;margin:0;}
        #header {font-weight: bold;background: #ccc;}
    </style>
</head>
<body>
    <div id="header">
        <form action="{% url 'cms:search' %}" method="get">
            <a href="{% url 'cms:home' %}">Home</a>&bull;
            <label for="q">Search:</label><input type="text" name="q">
        </form>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

cms/templates/cms/story_detail.html
{% extends 'cms/base.html' %}
{% block title %}{{ story.title }}{% endblock %}
{% block content %}
    <h1>{{ story.title }}</h1>
    <h2><a href="{% url 'cms:category' story.category.slug %}">{{ story.category.slug }}</a> </h2>
    <div id="story-body">
        {{ story.html_content|safe }}
    <p class="small">Updated {{ story.modified }}</p>
    </div>
{% endblock %}

cms/templates/cms/story_list.html
{% extends 'cms/base.html' %}
{% block content %}
    {% if heading %}
        <h1>{{ heading }}</h1>
    {% endif %}
    <ul id="story-list">
    {% for story in story_list %}
        <li><a href="{% url 'cms:story' story.slug %}">{{ story.title }}=={{ story.slug }}</a> </li>
    {% endfor %}
    </ul>
{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href= "{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gallery --{% block title  %}{% endblock %}</title>
    <style type="text/css">
        body{margin: 30px;background: #ffffff}
        h1 {background: #ccf;padding: 20px}
        h2 {background:#ddf;padding: 10px}
        h3 {background:#eef;padding: 5px}
        table {width:100%}
        table th {
            text-align: left;}
    </style>
</head>
    <h1>Gallery</h1>
    {% block content %}{% endblock %}
<body>

</body>
</html>

templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog</title>
</head>
<body>
    {% for post in posts %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
        <p>{{ post.timestamp }}</p>
    {% endfor %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content  %}
    <table>
        <tr>
            {% for item in items %}


                <td>
                    <a href="{{ item.get_absolute_url }}">{{ item.name }}<\<br>
                    {% if item.photo_set.count %}
                        <img src="{{ item.photo_set.all.0.image.thumb_url }}"/>
                    {% endif  %}
                    </a>

                </td>
            {% endfor %}
        </tr>

    </table>




{% endblock %}